### PR TITLE
Space traveler's Hub React project

### PR DESCRIPTION
**Pull request by MacCrazyman**
# Space traveler's Hub React project 🚀 

This PR fetches information from SpaceX data API and the site implements the following features:

* Renders Missions and Rockets information.
* User is able to book Rockets and Missions.
* Booked Rockets and Missions are displayed on the user's profile.
* The site indicates when the user has booked for a rocket or mission.

### CODE REVIEW

**Review by DammyShittu — CHANGES_REQUESTED** [review]
Hi @MacCrazyman  @rtonata88, 

You have built an amazing project 💯 

The user interface is topnotch 🌟

Great job 🤸‍♂️ 

However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- According to the requirements, kindly use conditions rendering for Missions and Rockets

Please check React's [documentation](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator) on conditional rendering to learn more 😉 .

- To make your app more complete, kindly add some tests with React testing Library and Jest. Tests are an essential part of development as they help us ascertain that our app works well under all circumstances. 😀 

# Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MacCrazyman** [comment]
> Hi @MacCrazyman @rtonata88,
> 
> You have built an amazing project 💯
> 
> The user interface is topnotch 🌟
> 
> Great job 🤸‍♂️
> 
> However, there are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Required Changes ♻️
> * According to the requirements, kindly use conditions rendering for Missions and Rockets
>   
>   Please check React's [documentation](https://reactjs.org/docs/conditional-rendering.html#inline-if-with-logical--operator) on conditional rendering to learn more 😉 .
> * To make your app more complete, kindly add some tests with React testing Library and Jest. Tests are an essential part of development as they help us ascertain that our app works well under all circumstances. 😀
> 
> # Cheers and Happy coding!👏👏👏
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thanks for your kind review @DammyShittu .

I would appreciate it if you can provide us with a wider explanation of the required changes regarding conditional rendering by pointing out the parts of the code.

As far as I can see, we have implemented conditional rendering in different parts of the code using different approaches, like in the example below:
https://github.com/MacCrazyman/space-traveler-hub-react/blob/70754c13348a8e7f5562d73020f4ef881a24cf71/src/component/Rocket.js#L11-L31

The approach using `if` - `else` statement is described in the [documentation](https://reactjs.org/docs/conditional-rendering.html#element-variables) and has been implemented to render complex elements.

On the other hand, we have also used inline conditionals to manipulate the classes and the content of the components:

https://github.com/MacCrazyman/space-traveler-hub-react/blob/70754c13348a8e7f5562d73020f4ef881a24cf71/src/component/missions.js#L36-L37

https://github.com/MacCrazyman/space-traveler-hub-react/blob/70754c13348a8e7f5562d73020f4ef881a24cf71/src/component/missions.js#L42-L43

Inline conditionals are also described in the [React documentation](https://reactjs.org/docs/conditional-rendering.html#inline-if-else-with-conditional-operator)

Please let us know in which other parts of the code should we implement the conditional rendering to meet the project requirements.

Once again, thanks for your kindness.

Regards.

**Comment by DammyShittu** [comment]
Hi @MacCrazyman, 

Thank you for pointing these out. I sure have learned a thing or two this morning. 😉 

Please, proceed to work on other changes that were suggested.

I'm sorry for the late response.

Keep soaring 🚀

**Comment by MacCrazyman** [comment]
Thanks for the Feedback @DammyShittu .

We are moving on to add test cases.

**Review by addod19 — APPROVED** [review]
### Hi @MacCrazyman and @rtonata88, 

Your project is complete! Nice job adding the test suite :100:  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Optional
- [ ] It would be better if we add negative test cases to our test so ensure all test cases are covered

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
